# Generated by Django 4.0.6 on 2022-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhome', '0002_studentregistrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherregistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('class1', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
