# Generated by Django 4.0.6 on 2022-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhome', '0003_teacherregistrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('is_student', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
    ]
