# Generated by Django 4.0.6 on 2022-08-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhome', '0004_checkstudent_checkteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkteacher',
        ),
        migrations.RemoveField(
            model_name='checkstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='checkstudent',
            name='is_student',
        ),
        migrations.AddField(
            model_name='checkstudent',
            name='check_type',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
