# Generated by Django 4.0.6 on 2022-08-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhome', '0005_delete_checkteacher_remove_checkstudent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrations',
            name='email',
        ),
    ]
