# Generated by Django 4.0.6 on 2022-08-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolhome', '0006_remove_studentregistrations_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherregistrations',
            old_name='email',
            new_name='div',
        ),
        migrations.RemoveField(
            model_name='teacherregistrations',
            name='subject',
        ),
    ]
